### ISSUE TITLE
请教一下有没有在电视上能直接用组播源的APP

### ISSUE THREAD

**Issue by BlueCatEatLala** [xisohi/IPTV-Multicast-source#2]
试了一下TiviMate和几个版本的Tvbox，都不能直接用rtp源。IPTV pro能播，但是一直有个加载中的提示（好像是bug）。Kodi可以播就是界面友好度跟前几个差太多了，难道只能用VLC吗~

**Comment by xisohi** [comment]
电视系统是安卓几的？

**Comment by BlueCatEatLala** [comment]
安卓11。用手机和电视都试了一下，rtp://形式的源只有kodi能播，很丝滑。其他最后试的是Fongmi（播放地址加载失败 错误代码1004）

**Comment by xisohi** [comment]
[Q版和fongmi可以直接食用！
![fongmi](https://github.com/user-attachments/assets/e3ab386f-8b01-402a-a09a-b990ea21d1c0)
![Q](https://github.com/user-attachments/assets/2036d198-d02c-4d0f-bfcb-63ec9228adc1)
